# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Coffee(object):
    def setupUi(self, Coffee):
        Coffee.setObjectName("Coffee")
        Coffee.resize(900, 700)
        Coffee.setMinimumSize(QtCore.QSize(900, 700))
        Coffee.setMaximumSize(QtCore.QSize(900, 700))
        Coffee.setBaseSize(QtCore.QSize(900, 700))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Coffee.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Coffee)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableView(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 10, 880, 620))
        self.table.setObjectName("table")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(10, 640, 200, 30))
        self.add_button.setObjectName("add_button")
        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setGeometry(QtCore.QRect(220, 640, 200, 30))
        self.edit_button.setObjectName("edit_button")
        self.arabic_button = QtWidgets.QRadioButton(self.centralwidget)
        self.arabic_button.setGeometry(QtCore.QRect(430, 640, 100, 30))
        self.arabic_button.setObjectName("arabic_button")
        self.robust_button = QtWidgets.QRadioButton(self.centralwidget)
        self.robust_button.setGeometry(QtCore.QRect(540, 640, 100, 30))
        self.robust_button.setObjectName("robust_button")
        self.liberica_button = QtWidgets.QRadioButton(self.centralwidget)
        self.liberica_button.setGeometry(QtCore.QRect(650, 640, 120, 30))
        self.liberica_button.setObjectName("liberica_button")
        self.excelsa_button = QtWidgets.QRadioButton(self.centralwidget)
        self.excelsa_button.setGeometry(QtCore.QRect(770, 640, 120, 30))
        self.excelsa_button.setObjectName("excelsa_button")
        Coffee.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Coffee)
        self.statusbar.setObjectName("statusbar")
        Coffee.setStatusBar(self.statusbar)

        self.retranslateUi(Coffee)
        QtCore.QMetaObject.connectSlotsByName(Coffee)

    def retranslateUi(self, Coffee):
        _translate = QtCore.QCoreApplication.translate
        Coffee.setWindowTitle(_translate("Coffee", "Coffee"))
        self.add_button.setText(_translate("Coffee", "Добавить Запись"))
        self.edit_button.setText(_translate("Coffee", "Редактировать Запись"))
        self.arabic_button.setText(_translate("Coffee", "Арабика"))
        self.robust_button.setText(_translate("Coffee", "Робуста"))
        self.liberica_button.setText(_translate("Coffee", "Либерика"))
        self.excelsa_button.setText(_translate("Coffee", "Эксцельса"))
